title: Aimed At The Stars
email: gtbUncleMattMan@AimedAtTheStars.org
description: |-
  Aimed At The Stars, Elite: Dangerous Squadron (ID: STGR) and Player Minor Faction
repository: irtnog/aimedatthestars.org
plugins:
  - jekyll-feed
  - jekyll-sitemap
header-pages:
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
